services:
  # Backend Node / Express Web Service
  - type: web
    name: fashion-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MYSQL_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: fashion
      - key: DB_DIALECT
        value: mysql
      - key: DB_SSL
        value: false
      - key: JWT_SECRET_ADMIN
        generateValue: true
      - key: JWT_SECRET_CUSTOMER
        generateValue: true
      - key: JWT_SECRET_VENDOR
        generateValue: true
      - key: REFRESH_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false

  # Frontend React / Vite Static Site
  - type: web
    name: fashion-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
      - key: VITE_API_TIMEOUT
        value: 30000
